### ISSUE TITLE
Attribute Error in TopNetblocks module - whois_cidr.py

### ISSUE THREAD

**Issue by Rich5** [ChrisTruncer/Just-Metadata#21]
You selected the "TopNetblocks" module, how many CIDR blocks do you want returned?
Ex: 10

[>] Total: 10
Traceback (most recent call last):
  File "JustMetadata.py", line 94, in <module>
    the_conductor.menu_system()
  File "/root/Tools/Just-Metadata/common/orchestra.py", line 275, in menu_system
    self.user_command.split()[1])
  File "/root/Tools/Just-Metadata/common/orchestra.py", line 319, in run_analyze_command
    analytics_obj.analyze(self.system_objects)
  File "modules/analytics/whois_cidr.py", line 28, in analyze
    if 'asn_cidr' in single_ip[0].ip_whois.keys():
AttributeError: 'str' object has no attribute 'keys'

**Comment by ChrisTruncer** [comment]
Did you collect the data, and when asked for the number of results you want returned, you typed "10" and it failed?  Or did you try running that without collecting the data?

Just want to make sure I can replicate the crash and then fix it

**Comment by ChrisTruncer** [comment]
Odd, I can't seem to re-create this issue.  When you get a chance, can you just let me know how to replicate it?

Thanks!

**Comment by Rich5** [comment]
Sure. I'm thinking some of this is because information is not coming back for the targets. So maybe there are some null datasets breaking the analysis. Here's the basic steps for the following targets:

52.34.119.26
52.37.68.150

_The IPs are not sensitive. Just some brute-force attempts on one of my servers._

load targets.txt 
gather all
analyze all

You selected the "TopNetblocks" module, how many CIDR blocks do you want returned?
Ex: 10

[>] Total: 10
Traceback (most recent call last):
File "JustMetadata.py", line 94, in 
the_conductor.menu_system()
File "/root/Tools/Just-Metadata/common/orchestra.py", line 275, in menu_system
self.user_command.split()[1])
File "/root/Tools/Just-Metadata/common/orchestra.py", line 319, in run_analyze_command
analytics_obj.analyze(self.system_objects)
File "modules/analytics/whois_cidr.py", line 28, in analyze
if 'asn_cidr' in single_ip[0].ip_whois.keys():
AttributeError: 'str' object has no attribute 'keys'

**Comment by ChrisTruncer** [comment]
<img width="752" alt="justmetadata screenshot" src="https://cloud.githubusercontent.com/assets/1674822/13850638/1f36da8c-ec5b-11e5-9a48-9b70642aa613.png">

Odd, It's coming back for me with those IPs.  I'll add in a check to make sure it's the correct datatype, although I feel it's a little bit of a bandaid for a different problem.

This should fix it though, so I'll get it added shortly.

**Comment by Rich5** [comment]
That is weird. Now I'm thinking this is related to the network I'm on, and connected to the whois and JSON errors. See below:

Querying Shodan for information about 52.34.119.26
Querying Shodan for information about 52.37.68.150
Getting info on... 52.34.119.26
Getting info on... 52.37.68.150
Gathering whois information about 52.34.119.26
*_Could not connect online to lookup whois for *_
Gathering whois information about 52.37.68.150
*_Could not connect online to lookup whois for *_
Grabbing list of TOR exit nodes..
Grabbing attacker IP list from the Animus project...
Grabbing EmergingThreats list...
Grabbing AlienVault reputation list...
Grabbing Blocklist.de info...
Grabbing DragonResearch's SSH list...
Grabbing DragonResearch's VNC list...
Grabbing NoThinkMalware list...
Grabbing NoThinkSSH list...
Grabbing Feodo list...
Grabbing antispam spam list...
Grabbing malc0de list...
Grabbing MalwareBytes list...
*_Error loading JSON response for 
Error loading JSON response for *_

**Comment by ChrisTruncer** [comment]
Hm... it might be possible.  You happen to have a different network connection you could test from that isn't behind the same network?

The other bugs were definitely problems, this is just the only one that I can't replicate at the moment.

**Comment by Rich5** [comment]
Not at the moment. I can check later this afternoon on a different network.

**Comment by ChrisTruncer** [comment]
OK, that would work, just let me know what you encounter.

In the meantime, I am basically catching the error if it isn't a python dictionary, so it will just alert out that the data isn't in the expected format, but continue on.

If you find anymore issues... definitely let me know!  Thanks again.

**Comment by Rich5** [comment]
After a bit of looking around I think there are two issues here. The first one I believe you fixed by adding the exception handler. Basically it looks like ipwhois isn't able to connect and it's not returning the expected data somewhere in your object. 

The second (root) problem, for me at least, is that I'm behind a proxy. Now ipwhois does support proxy settings, but it doesn't look like it works for Python 2.7. Here's why:

From the ipwhois documents:
Use a proxy

```
>>>> from urllib import request
>>>> from ipwhois import IPWhois
>>>> handler = request.ProxyHandler({'http': 'http://192.168.0.1:80/'})
>>>> opener = request.build_opener(handler)
>>>> obj = IPWhois('74.125.225.229', proxy_opener = opener)
```

This is all well and good except when you try to use a proxy like this in Python 2.7 you get the following import error:

```
root@kali:~# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib import request
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name request
>>> 

```

That's because the request object doesn't exist in urllib under Python 2.7. See: https://docs.python.org/3/library/urllib.request.html

Ok so the next natural step is to try an equivalent library like urllib2, and try to build an opener using something like this:

```
proxy = urllib2.ProxyHandler({'http': '127.0.0.1'})
opener = urllib2.build_opener(proxy)
urllib2.install_opener(opener)
```

Passing this opener to the ipwhois class gives the same error, and I'm not sure why since the ipwhois code seems to support using urllib2 - (https://github.com/secynic/ipwhois/blob/master/ipwhois/net.py#L56)

```

>>> from ipwhois import IPWhois
>>> import urllib2
>>> proxy = urllib2.ProxyHandler({'http': '1.1.1.1:3128'})
>>> opener = urllib2.build_opener(proxy)
>>> urllib2.install_opener(opener)
>>> obj = IPWhois('52.34.119.26', proxy_opener=opener)
>>> results = obj.lookup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/ipwhois.py", line 115, in lookup
    asn_data, response = self.net.lookup_asn(retry_count)
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 623, in lookup_asn
    retry_count
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 517, in get_http_json
    raise HTTPLookupError('HTTP lookup failed for %r.' % url)
ipwhois.exceptions.HTTPLookupError: HTTP lookup failed for 'http://whois.arin.net/rest/nets;q=52.34.119.26?showDetails=true&showARIN=true'.
```

But if I copy the line into my browser it works just fine:

![image](https://cloud.githubusercontent.com/assets/7902735/13855577/83bedfd6-ec47-11e5-926f-7af8c2e045eb.png)

Ultimately, this looks like an environmental issue with proxies etc. Not necessarily you're problem, but maybe this will save you some time if others have this issue. Thanks for the tool!

**Comment by ChrisTruncer** [comment]
Wow, that's really good research getting to the root of the problem.  Thanks for taking the time to investigate that, it definitely helps me out.

After seeing everything you found, I'd have to agree with your conclusions.  That does seem really odd, and I'm (obviously) running into the same 2.7 issue with importing request.

I think for now I'm going to just have to leave this as a limitation with the library, but potentially circle back and look at different whois lookup libraries in the future.

Thanks again, and given all that good information, at least if anyone else has this problem they will now be able to understand it.
