### ISSUE TITLE
Python Module netaddr

### ISSUE THREAD

**Issue by fuuddanni** [ChrisTruncer/Just-Metadata#32]
Hi Chris, can you please give me some hints why i got this Module Error. Pip says that it is already satisfied:

E:\Github\Metadata>JustMetadata.py
Traceback (most recent call last):
  File "E:\Github\Metadata\JustMetadata.py", line 13, in <module>
    from common import orchestra
  File "E:\Github\Metadata\common\orchestra.py", line 12, in <module>
    import netaddr
ImportError: No module named netaddr

E:\Github\Metadata>pip install netaddr --upgrade
Requirement already up-to-date: netaddr in e:\python27\lib\site-packages

Thank you.

**Comment by ChrisTruncer** [comment]
I can't say why that isn't working for you.  If you run just the python interpreter and then try to import the library, does it work?

Also, I can't state how well this works on Windows.  Theoretically it should be fine, but I don't develop in a Windows system.

**Comment by fuuddanni** [comment]
Thank you for your answer, but now it seems to work with virtualenv (workon). I´ve just reinstalled the dependencies in virtualenv. 
################################################################################

# Just-Metadata

################################################################################

ip_info => Display's all info about an IP address
save    => Saves IPs and attributes to disk for reloading in the future (opt: filename)
gather => Requests information and gathers statistics on loaded IP addresses
export => Exports all data on all IPs to CSV (opt: filename)
exit    => Exits out of Just-Metadata
import  => Import's saved state into Just Metadata
analyze => Run [module] on the loaded IP addresses
help    => Displays commands and command descriptions
load    => Loads IPs into the framework for analysis
list    => Prints loaded [analysis] or [gather] modules

[>] Please enter a command:

**Comment by ChrisTruncer** [comment]
Great, glad to hear it's working for you!
