### ISSUE TITLE
Exception error - help needed

### ISSUE THREAD

**Issue by xsallowed** [ChrisTruncer/Just-Metadata#35]
I am getting following error while running Just-metadata.py 

---
# Just-Metadata
###### 

Traceback (most recent call last):
  File "./JustMetadata.py", line 93, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/home/tahir/Just-Metadata/common/orchestra.py", line 67, in **init**
    self.load_intelgathering_functions()
  File "/home/tahir/Just-Metadata/common/orchestra.py", line 179, in load_intelgathering_functions
    name.replace("/", ".").rstrip('.py'), name)
  File "modules/intelgathering/whois_info.py", line 6, in <module>

**Comment by ChrisTruncer** [comment]
Hi again,

Like I said in the last issue you opened, please run the setup script.  It will install the dependencies.

**Comment by xsallowed** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Hi ChrisI tried that as well but unfortunately I am getting errors in there as well. If you can list down the dependencies I will install manually.

ThanksTS

On Wednesday, September 21, 2016, 1:18 AM, ChrisTruncer notifications@github.com wrote:

Hi again,

Like I said in the last issue you opened, please run the setup script. It will install the dependencies.

**Comment by ChrisTruncer** [comment]
Please look at the setup script, they are in listed there.
