### ISSUE TITLE
Getting an import error when I try to run Just-Metadata.py

### ISSUE THREAD

**Issue by Shane-armbrister** [ChrisTruncer/Just-Metadata#42]
Traceback (most recent call last):
  File "./JustMetadata.py", line 13, in <module>
    from common import orchestra
  File "/Users/me/Just_Metadata/Just-Metadata/common/orchestra.py", line 12, in <module>
    import netaddr
ImportError: No module named netaddr

**Comment by ChrisTruncer** [comment]
Did you run the setup script? Can you give me any info such as the distro you are using?

**Comment by Shane-armbrister** [comment]
Hey I ran the set up script.  Python 3.7

Thank you,

Shane Armbrister

**Comment by ChrisTruncer** [comment]
I had asked which Linux distro that you are using. Also, this script uses Python 2.

**Comment by ChrisTruncer** [comment]
Closing since I haven't heard back.

Please use Python 2 and that will likely fix your error

**Comment by Shane-armbrister** [comment]
Hey Chris,
My apologize for not getting back.  Thank you for the information and for getting back to me so quickly I appreciate it.  My colleague has this application working on his system and I'd like to say Great freaking job!  This application is soo cool and wildly beneficial.  Thanks again for the help.  I can definitely take it from here to get it fixed.
