### ISSUE TITLE
Modules not loading

### ISSUE THREAD

**Issue by mkayoh** [ChrisTruncer/Just-Metadata#8]
IPs load correctly into the framework but whenever I try to run any module either with analyze or gather I keep getting the following error:

[_] Error: You didn't provide a valid module!
[_] Please re-run and use a valid module.

**Comment by ChrisTruncer** [comment]
Can you please provide the full console output from you loading, up to attempting to running those commands?  I can’t re-create your problem currently here, and this is the first time that I’ve heard anyone mention this, which would normally be a pretty big issue.

Please copy your full console output into pastebin, and paste that link here.  Also, please provide OS info as well.

---

Christopher Truncer
@christruncer

On June 23, 2015 at 6:44:25 AM, mkayoh (notifications@github.com) wrote:

IPs load correctly into the framework but whenever I try to run any module either with analyze or gather I keep getting the following error:

[] Error: You didn't provide a valid module!
[] Please re-run and use a valid module.

**Comment by mkayoh** [comment]
Should have specified it more, everything seems to work when running the script from bash and passing arguments to it but its own CLI doesn't seem to find those modules.

So running a command like ./JustMetadata.py -l /home/ubuntu/iplist -g Shodan does work but running the same thing inside the CLI doesn't.

Here's the complete paste which sadly is not much http://pastebin.com/Cg5Mn8mt

$ uname -r
Linux version 3.13.0-46-generic (buildd@tipua) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015

And if it makes any difference the Python version I'm running is 2.7.6

**Comment by ChrisTruncer** [comment]
Hey there,

I'm trying to re-create that, but I seem to be running into issues.  I am able to run this from the menu-driven interface, but it seems like you aren't (http://pastebin.com/HWqDz6dJ).  Do you have the latest version of Just-Metadata?  As a random test (if you happen to have a spare VM free) do you have an instance of Debian Stable, or Kali, you could try the same thing on?

Also, I know that there are/were some install versions getting Just-Metadata working on Ubuntu.  It's really odd and I wasn't 100% able to figure it out yet (which was why I have been saying this should initially be used on Kali and Debian), but the error you are getting makes it look like you got past any potential setup issues.  Also, when I run this from the command line, it looks to work too (http://pastebin.com/mXSjLY0B).  

I wish I could give you something to look at, but I just can't seem to recreate that when trying to run essentially the same commands.  Worst case, maybe try re-cloning again and see if it works then?

**Comment by ChrisTruncer** [comment]
Were you able to try any of these suggestions?

**Comment by mkayoh** [comment]
Sorry been very busy. Unfortunately I do not right now have access to other VMs so I can't test those other distros. The Ubuntu image I'm using is very bare bones from uvt-kvm (https://help.ubuntu.com/lts/serverguide/cloud-images-and-uvtool.html) so it's most likely missing some dependencies/running older version of some.
