### ISSUE TITLE
IPDefinedError import is missing

### ISSUE THREAD

**Issue by nicolasvillatte** [ChrisTruncer/Just-Metadata#9]
File "modules/intelgathering/whois_info.py", line 6, in <module>
    from ipwhois.ipwhois import IPDefinedError
ImportError: cannot import name IPDefinedError

Where should I get it from?

**Comment by nicolasvillatte** [comment]
Found it... You need to correct your whois_info.py module:
change:   from ipwhois.ipwhois import IPDefinedError
with:        from ipwhois.exceptions import IPDefinedError

**Comment by ChrisTruncer** [comment]
merged in :)

Thanks for your help and submitting the patch!
